# Copyright © 2026 - Homewood Health Inc.

HOMEWEB_BASE_URL = "https://homeweb.ca"
HOMEWEB_BETA_BASE_URL = "https://beta.homeweb.ca"
HOMEWEB_STAGING_BASE_URL = "https://staging.homeweb.ca"
HOMEWEB_LOCAL_BASE_URL = "https://qclient.test"
CUSTOMER_PORTAL_BASE_URL = "https://portal.homewoodhealth.com"
QUANTUM_API_BASE_URL = "https://api.homewoodhealth.io"
QUANTUM_API_BETA_BASE_URL = "https://betaapi.homewoodhealth.io"
QUANTUM_API_STAGING_BASE_URL = "https://stgapi.homewoodhealth.io"
SENTIO_BETA_CLIENT_BASE_URL = "https://beta.sentioapp.com"
SENTIO_BETA_PROVIDER_BASE_URL = "https://beta-portal.sentioapp.com"

HOMEWEB_LOCAL_DOMAIN = "qclient.test"
HOMEWEB_DOMAIN = "homeweb"
HOMEWEB_BETA_DOMAIN = "beta.homeweb"
HOMEWEB_STAGING_DOMAIN = "staging.homeweb"
CUSTOMER_PORTAL_DOMAIN = "portal.homewoodhealth"
QUANTUM_API_DOMAIN = "api.homewoodhealth"
QUANTUM_API_BETA_DOMAIN = "betaapi.homewoodhealth"
QUANTUM_API_STAGING_DOMAIN = "stgapi.homewoodhealth"
SENTIO_DOMAIN = "sentioapp"
SENTIO_BETA_CLIENT_DOMAIN = "beta.sentioapp"
SENTIO_BETA_PROVIDER_DOMAIN = "beta-portal.sentioapp"
LIFESTAGE_DOMAIN = "lifestage"
LIFESTYLE_DOMAIN = "healthycommunity"
